/*
 * gozd design tokens Tier 1 (primitives) を Adobe Leonardo の contrast-driven
 * algorithm で生成し、CSS file (dist/tokens.generated.css) として出力する。
 *
 * Tailwind v4 の `@theme inline` semantic alias 層は consumer 側 (renderer の
 * main.css) が定義する。この package は primitive 層のみを責任範囲とする:
 *   - gray 12-step solid + 12-step alpha (overlay 用)
 *   - intent hues (blue/red/green/amber/orange) 各 12-step solid
 *
 * Radix step → role 写像に揃えた WCAG2 contrast ratios:
 *   1     bg 自身
 *   2-5   bg / component bg (rest/hover/active)
 *   6-8   border (subtle/interactive/strong)
 *   9-10  solid bg (rest/hover)
 *   11    low-contrast text (WCAG2 8.0+)
 *   12    high-contrast text (WCAG2 14.0+)
 *
 * 再生成: pnpm install (prepare で自動) または pnpm --filter @gozd/design-tokens
 *         build。brand identity を変えたいときは BRAND を編集して再生成。
 */
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { Color, BackgroundColor, Theme } from "@adobe/leonardo-contrast-colors";
import chroma from "chroma-js";

const SCRIPT_REL_PATH = "packages/design-tokens/src/generateTokens.ts";
const OUTPUT_FILE = path.resolve(import.meta.dir, "../dist/tokens.generated.css");

const BRAND = {
  gray: "#888888",
  blue: "#3b82f6",
  red: "#ef4444",
  green: "#22c55e",
  amber: "#f59e0b",
  orange: "#f97316",
} as const;

const STEP_RATIOS_BG = [1.1, 1.3, 1.5, 1.8, 2.2, 2.8, 3.5, 4.5, 5.5, 8, 14];
const STEP_RATIOS_INTENT = [1.05, 1.15, 1.3, 1.5, 1.8, 2.2, 2.8, 3.5, 4.5, 5.5, 8, 14];

/* BackgroundColor scale 上で bg が位置する % (dark UI のため低い値) */
const DARK_LIGHTNESS = 11;

/* Leonardo の chroma-js module 拡張が型推論を unknown に倒すため明示 cast */
function oklchOf(hex: string): [number, number, number] {
  return (chroma(hex) as unknown as { oklch: () => [number, number, number] }).oklch();
}

function toOklch(hex: string): string {
  const [l, c, h] = oklchOf(hex);
  const lr = (Math.round(l * 1000) / 1000).toString();
  const cr = (Math.round(c * 1000) / 1000).toString();
  /* chroma=0 (pure gray) は NaN hue を 0 に正規化 */
  const hr = Number.isNaN(h) ? "0" : (Math.round(h * 10) / 10).toString();
  return `oklch(${lr} ${cr} ${hr})`;
}

/* white overlay on bg で色 T を再現する alpha を計算
 * formula (linear RGB): T = white * a + bg * (1 - a) → a = (T - bg) / (1 - bg)
 * gray は無彩色なので lightness 1 channel で計算可能 */
function alphaForGray(target: string, bg: string): string {
  const t = oklchOf(target)[0];
  const b = oklchOf(bg)[0];
  const a = Math.max(0, Math.min(1, (t - b) / (1 - b)));
  return `oklch(1 0 0 / ${Math.round(a * 1000) / 1000})`;
}

const gray = new BackgroundColor({
  name: "gray",
  colorKeys: [BRAND.gray],
  colorSpace: "OKLCH",
  ratios: STEP_RATIOS_BG,
});

const intents = (["blue", "red", "green", "amber", "orange"] as const).map(
  (name) =>
    new Color({
      name,
      colorKeys: [BRAND[name]],
      colorSpace: "OKLCH",
      ratios: STEP_RATIOS_INTENT,
    }),
);

/* gray を colors にも入れる: BackgroundColor は bg 単一点を提供するだけで、
 * gray scale (12 step) は contrastColors の colors array 経由でしか取れない
 * (Adobe Spectrum 公式 pattern) */
const theme = new Theme({
  colors: [gray, ...intents],
  backgroundColor: gray,
  lightness: DARK_LIGHTNESS,
  contrast: 1,
  output: "HEX",
  formula: "wcag2",
});

type ContrastGroup = { name: string; values: { value: string }[] };
const [bgEntry, ...groups] = theme.contrastColors as [
  { background: string },
  ...ContrastGroup[],
];

/* gray scale: step 1 = bg 自身、steps 2..12 = ratios の各点 */
const grayGroup = groups.find((g) => g.name === "gray");
if (grayGroup === undefined) throw new Error("Leonardo did not return gray group");
const grayHexes: string[] = [bgEntry.background, ...grayGroup.values.map((v) => v.value)];
if (grayHexes.length !== 12) throw new Error(`expected 12 gray steps, got ${grayHexes.length}`);

const lines: string[] = [
  `/* Auto-generated by ${SCRIPT_REL_PATH} — do not edit. */`,
  `/* Tier 1: gozd design token primitives (Adobe Leonardo, dark mode) */`,
  ``,
  `:root {`,
  `  /* gray: 12-step solid */`,
];
for (let i = 0; i < grayHexes.length; i++) {
  lines.push(`  --gray-${i + 1}: ${toOklch(grayHexes[i])};`);
}
lines.push(``);
lines.push(`  /* gray: 12-step alpha (white overlay matched to gray scale) */`);
for (let i = 0; i < grayHexes.length; i++) {
  lines.push(`  --gray-a${i + 1}: ${alphaForGray(grayHexes[i], grayHexes[0])};`);
}

for (const intent of intents) {
  const group = groups.find((g) => g.name === intent.name);
  if (group === undefined) throw new Error(`missing ${intent.name} group`);
  const hexes = group.values.map((v) => v.value);
  if (hexes.length !== 12) throw new Error(`expected 12 ${intent.name} steps, got ${hexes.length}`);
  lines.push(``);
  lines.push(`  /* ${intent.name}: 12-step solid */`);
  for (let i = 0; i < hexes.length; i++) {
    lines.push(`  --${intent.name}-${i + 1}: ${toOklch(hexes[i])};`);
  }
}

lines.push(`}`);
lines.push(``);

await mkdir(path.dirname(OUTPUT_FILE), { recursive: true });
await writeFile(OUTPUT_FILE, lines.join("\n"));
console.error(
  `generated ${grayHexes.length + intents.length * 12} primitives + ${grayHexes.length} alpha → ${OUTPUT_FILE}`,
);
