// RPC メッセージ型の barrel（旧 `.proto` SSOT の後継。手書き TS 型が SSOT）。
//
// ワイヤ契約: renderer ↔ main の request / response は Electron IPC の structured clone で
// plain data（JSON 形 + `WireBytes`）をそのまま運ぶ。Unix ソケットの ClientMessage は
// NDJSON（JSON 1 行）で、socket を通る型にバイナリは載せない。フィールド名は
// 旧 proto3 JSON mapping の lowerCamelCase を踏襲（永続化 JSON のキーと一致）。
// `?` フィールドは undefined（永続化 JSON ではキー不在）で未設定を表現する。
// 永続化ファイル（config.json / app-state.json / tasks.json 等）も同じ型で読み書きし、
// 旧ファイルの欠落フィールドは main 側 store の load 時に default 充填する。

export type {
  AppConfig,
  EnsureAppConfigFileRequest,
  EnsureAppConfigFileResponse,
  LoadAppConfigRequest,
  LoadAppConfigResponse,
  SaveAppConfigRequest,
  SaveAppConfigResponse,
  AppConfigChangePayload,
} from "./appConfig";
export type {
  AppState,
  LoadAppStateRequest,
  LoadAppStateResponse,
  SaveAppStateRequest,
  SaveAppStateResponse,
  RepoList,
  SidebarRepo,
  WorktreeCacheEntry,
} from "./appState";
export type {
  ClaudeSessionLogRequest,
  ClaudeSessionLogResponse,
  ClaudeSessionRemoveByPtyRequest,
  ClaudeSessionRemoveByPtyResponse,
  ReviveSessionInfo,
  ReviveSessionListRequest,
  ReviveSessionListResponse,
  ReviveSessionRequest,
  ReviveSessionResponse,
} from "./claudeSession";
export type { ClipboardCopyFilesRequest, ClipboardCopyFilesResponse } from "./clipboard";
export type {
  ClientMessage,
  ClientReply,
  HookMessage,
  NewWorktreeMessage,
  OpenMessage,
} from "./clientMessage";
export type {
  FileReadResult,
  GhRef,
  GitCommit,
  GitFileChange,
  GitIssue,
  GitPullRequest,
  GitPullRequestBadge,
  GitPullRequestCheckState,
  GitPullRequestStack,
  Task,
  UpstreamStatus,
  WireBytes,
  WorktreeEntry,
} from "./common";
export type { EchoRequest, EchoResponse } from "./echo";
export type {
  FsReadDirEntry,
  FsReadDirRealTarget,
  FsReadDirRequest,
  FsReadDirResponse,
  FsReadFileAbsoluteRequest,
  FsReadFileAbsoluteResponse,
  FsExistsAbsoluteRequest,
  FsExistsAbsoluteResponse,
  FsReadFileRequest,
  FsReadFileResponse,
  FsStatRequest,
  FsStatResponse,
  FsUnwatchAllRequest,
  FsUnwatchAllResponse,
  FsUnwatchFileAbsoluteRequest,
  FsUnwatchFileAbsoluteResponse,
  FsUnwatchRequest,
  FsUnwatchResponse,
  FsWatchFileAbsoluteRequest,
  FsWatchFileAbsoluteResponse,
  FsWatchRequest,
  FsWatchResponse,
  FsWriteFileAbsoluteRequest,
  FsWriteFileAbsoluteResponse,
  FsWriteFileRequest,
  FsWriteFileResponse,
  FsChangePayload,
  FsChangeAbsolutePayload,
} from "./fs";
export type {
  CreateTaskWorktreeRequest,
  CreateTaskWorktreeResponse,
  CreateWorktreeRequest,
  CreateWorktreeResponse,
  DiffExpandedLine,
  DiffHunk,
  DiffLineKind,
  GhErrorKind,
  GitBlameCommit,
  GitBlameLineRequest,
  GitBlameLineResponse,
  GitCommitFilesRequest,
  GitCommitFilesResponse,
  GitDiffExpandLinesRequest,
  GitDiffExpandLinesResponse,
  GitDiffHunksRequest,
  GitDiffHunksResponse,
  GitFetchRemotesRequest,
  GitFetchRemotesResponse,
  GitGithubIdentityRequest,
  GitGithubIdentityResponse,
  GitIssueListRequest,
  GitIssueListResponse,
  GitLogFileRequest,
  GitLogFileResponse,
  GitLogLineRequest,
  GitLogLineResponse,
  GitLogRequest,
  GitLogResponse,
  GitLsFilesRequest,
  GitLsFilesResponse,
  GitLsTreeRequest,
  GitLsTreeResponse,
  GitMergeBaseRequest,
  GitMergeBaseResponse,
  GitItemKind,
  GitMyWorkAxisKey,
  GitMyWorkGroup,
  GitMyWorkItem,
  GitMyWorkRequest,
  GitMyWorkResponse,
  GitMyWorkWebLink,
  GitPullRequestReviewDecision,
  GitPrDiffFilesRequest,
  GitPrDiffFilesResponse,
  GitPrListRequest,
  GitPrListResponse,
  GitPrsForBranchesRequest,
  GitPrsForBranchesResponse,
  GitReadBlobRequest,
  GitReadBlobResponse,
  GitResetMixedRequest,
  GitResetMixedResponse,
  GitRevReachableRequest,
  GitRevReachableResponse,
  GitShowCommitFileRequest,
  GitShowCommitFileResponse,
  GitShowFileRequest,
  GitShowFileResponse,
  GitSubmoduleUrlRequest,
  GitSubmoduleUrlResponse,
  GitTreeEntry,
  GitViewerRequest,
  GitViewerResponse,
  GitWorktreeListRequest,
  GitWorktreeListResponse,
  GitWorktreeRemoveRequest,
  GitWorktreeRemoveResponse,
  NewWorktreePayload,
  BranchScope,
  SortMode,
} from "./gitOps";
export type {
  GitStatusRequest,
  GitStatusResponse,
  BranchChangePayload,
  RemoteRefsChangePayload,
  WorktreeChangePayload,
  GitStatusChangePayload,
} from "./gitStatus";
export { FS_EXISTS_ABSOLUTE_MAX_PATHS } from "./fs";
export { GIT_PULL_REQUEST_CHECK_STATES } from "./common";
export { GIT_MY_WORK_AXIS_KEYS, GIT_PULL_REQUEST_REVIEW_DECISIONS } from "./gitOps";
export { ghRefForIssue, ghRefForPr, ghRefLabel } from "./helpers";
export type {
  OpenExternalRequest,
  OpenExternalResponse,
  OpenFileRequest,
  OpenFileResponse,
  PickAndOpenRequest,
  PickAndOpenResponse,
  GozdOpenPayload,
} from "./open";
export type {
  PreviewHtmlUrlRequest,
  PreviewHtmlUrlResponse,
  PreviewReleaseHtmlRequest,
  PreviewReleaseHtmlResponse,
} from "./preview";
export type {
  ProjectConfig,
  ProjectConfigEnsureFileRequest,
  ProjectConfigEnsureFileResponse,
  ProjectConfigLoadRequest,
  ProjectConfigLoadResponse,
  ProjectConfigSaveRequest,
  ProjectConfigSaveResponse,
} from "./projectConfig";
export type {
  PtyKillRequest,
  PtyKillResponse,
  PtyResizeRequest,
  PtyResizeResponse,
  PtySpawnRequest,
  PtySpawnResponse,
  PtyWriteRequest,
  PtyWriteResponse,
  PtyTextPayload,
  PtyExitPayload,
} from "./pty";
export type {
  ServerAttribution,
  ServerEntry,
  ServerListRequest,
  ServerListResponse,
  ServerPortsChangePayload,
} from "./server";
export type {
  TaskAddRequest,
  TaskAddResponse,
  TaskList,
  TaskListRequest,
  TaskListResponse,
  TaskRemoveByWorktreeRequest,
  TaskRemoveByWorktreeResponse,
  TaskRemoveRequest,
  TaskRemoveResponse,
  TaskSetTerminalTitleRequest,
  TaskSetTerminalTitleResponse,
  TaskSetUserTitleRequest,
  TaskSetUserTitleResponse,
} from "./task";
export type {
  TextSearchCancelRequest,
  TextSearchCancelResponse,
  TextSearchLineResult,
  TextSearchMatchPayload,
  TextSearchMatchRange,
  TextSearchOptions,
  TextSearchQuery,
  TextSearchRequest,
  TextSearchResponse,
} from "./textSearch";
export type {
  VoicevoxCheckEngineRequest,
  VoicevoxCheckEngineResponse,
  VoicevoxLaunchRequest,
  VoicevoxLaunchResponse,
  VoicevoxListSpeakersRequest,
  VoicevoxListSpeakersResponse,
  VoicevoxSpeaker,
  VoicevoxSpeakRequest,
  VoicevoxSpeakResponse,
} from "./voicevox";
export type {
  WindowCloseRequest,
  WindowCloseResponse,
  WindowSetTitleContextRequest,
  WindowSetTitleContextResponse,
  WindowFullscreenChangePayload,
} from "./window";
export type { NotifyPayload, DebugLogPayload } from "./observability";
export type { HookPayload } from "./clientMessage";
export type { PushPayloadMap } from "./push";
