/**
 * `linguist-languages` (= GitHub Linguist の languages.yml を JS 化したもの) と
 * Shiki の `bundledLanguagesInfo` を交差させて、拡張子 / ファイル名 → Shiki BundledLanguage
 * の静的マップを生成する。
 *
 * 実行: bun packages/shiki-lang-map/scripts/generateExtensionLangMap.ts
 * 設計詳細: packages/shiki-lang-map/README.md
 */

import fs from "node:fs";
import path from "node:path";
import { bundledLanguagesInfo } from "shiki";
import * as linguist from "linguist-languages";

const OUTPUT_FILE = path.resolve(import.meta.dir, "../dist/extensionLangMap.generated.ts");

/** Linguist name (正規化済み: lowercase) → Shiki id。
 *
 * 単純な lowercase 一致では届かないものだけ列挙する。`name.toLowerCase()` で
 * Shiki id と一致するもの (`"swift" → "swift"`, `"rust" → "rust"`) は不要。
 */
const NAME_TO_SHIKI: Record<string, string> = {
  "c#": "csharp",
  "c++": "cpp",
  "f#": "fsharp",
  "objective-c": "objective-c",
  "objective-c++": "objective-cpp",
  shell: "shellscript",
  "visual basic .net": "vb",
  emacs_lisp: "emacs-lisp",
  "common lisp": "common-lisp",
  "emacs lisp": "emacs-lisp",
  "git config": "ini",
  "html+erb": "erb",
  "html+razor": "razor",
  "verilog": "verilog",
  "systemverilog": "system-verilog",
  "matlab": "matlab",
  "pascal": "pascal",
  "viml": "viml",
  "vim script": "viml",
  "make": "make",
  "makefile": "make",
  "dockerfile": "docker",
  "git attributes": "ini",
  "git revision list": "ini",
  "ignore list": "ini",
  "asciidoc": "asciidoc",
  "tex": "tex",
  "html+ecr": "html",
  "html+eex": "html",
  "html+php": "html",
  "less": "less",
  "scss": "scss",
  "sass": "sass",
  "css": "css",
  "stylus": "stylus",
};

const shikiIds = new Set<string>(bundledLanguagesInfo.map((l) => l.id));
// Shiki の alias (例: `"clj"` for `"clojure"`) も resolve できるので alias 集合も持つ
const shikiAliases = new Set<string>();
for (const info of bundledLanguagesInfo) {
  for (const a of info.aliases ?? []) shikiAliases.add(a);
}

interface LinguistLang {
  name: string;
  extensions?: readonly string[];
  filenames?: readonly string[];
  aliases?: readonly string[];
}

/** Linguist language entry から Shiki BundledLanguage id を解決する。
 *
 * Linguist の `name` と Shiki の `id` は必ずしも一致しない (例: Linguist
 * `"Protocol Buffer"` ↔ Shiki `"proto"`)。Linguist 側の `aliases` も走査することで
 * 表記揺れを吸収する。
 */
function resolveShikiId(lang: LinguistLang): string | undefined {
  const name = lang.name.toLowerCase();

  // 1. 明示 alias table (一番強い)
  const explicit = NAME_TO_SHIKI[name];
  if (explicit !== undefined) {
    return shikiIds.has(explicit) ? explicit : undefined;
  }

  // 2. lowercase 直接一致
  if (shikiIds.has(name)) return name;

  // 3. 空白 → hyphen
  const hyphenated = name.replace(/\s+/g, "-");
  if (shikiIds.has(hyphenated)) return hyphenated;

  // 4. Linguist 側の aliases (例: "Protocol Buffer" の aliases に "proto" が居る) を
  //    Shiki id / Shiki alias と突合する
  for (const a of lang.aliases ?? []) {
    const al = a.toLowerCase();
    if (shikiIds.has(al)) return al;
    const ah = al.replace(/\s+/g, "-");
    if (shikiIds.has(ah)) return ah;
    if (shikiAliases.has(al)) return al;
    if (shikiAliases.has(ah)) return ah;
  }

  // 5. Shiki alias 経由 fallback
  if (shikiAliases.has(name)) return name;
  if (shikiAliases.has(hyphenated)) return hyphenated;

  return undefined;
}

const extMap: Record<string, string> = {};
const filenameMap: Record<string, string> = {};

const allLangs = Object.values(linguist) as readonly LinguistLang[];
const sortedLangs = [...allLangs].sort((a, b) => a.name.localeCompare(b.name));

let matchedLangCount = 0;
let unmatchedLangCount = 0;
const unmatchedNames: string[] = [];

for (const lang of sortedLangs) {
  const shikiId = resolveShikiId(lang);
  if (shikiId === undefined) {
    unmatchedLangCount++;
    unmatchedNames.push(lang.name);
    continue;
  }
  matchedLangCount++;

  for (const ext of lang.extensions ?? []) {
    // ".swift" → "swift" / "..." (空文字含む) は skip
    const key = ext.replace(/^\./, "").toLowerCase();
    if (key === "") continue;
    // first-write-wins (Linguist の name アルファベット順で衝突解決)
    if (!(key in extMap)) extMap[key] = shikiId;
  }

  for (const filename of lang.filenames ?? []) {
    if (!(filename in filenameMap)) filenameMap[filename] = shikiId;
  }
}

// 出力: 拡張子は ASCII order でソート
const extEntries = Object.entries(extMap).sort(([a], [b]) => a.localeCompare(b));
const filenameEntries = Object.entries(filenameMap).sort(([a], [b]) => a.localeCompare(b));

function fmtEntry([key, value]: [string, string]): string {
  return `  ${JSON.stringify(key)}: ${JSON.stringify(value)},`;
}

const content = `// Auto-generated by apps/renderer/scripts/generateExtensionLangMap.ts — do not edit.
// Data source: GitHub Linguist (via linguist-languages npm) × Shiki BundledLanguage.
// Run \`bun apps/renderer/scripts/generateExtensionLangMap.ts\` to regenerate.

import type { BundledLanguage } from "shiki";

/** 拡張子 → Shiki BundledLanguage の対応表 (Linguist 由来) */
export const LINGUIST_EXTENSION_LANG_MAP = {
${extEntries.map(fmtEntry).join("\n")}
} as const satisfies Record<string, BundledLanguage>;

/** ファイル名 (拡張子なし、例: \`Dockerfile\`) → Shiki BundledLanguage (Linguist 由来) */
export const LINGUIST_FILENAME_LANG_MAP = {
${filenameEntries.map(fmtEntry).join("\n")}
} as const satisfies Record<string, BundledLanguage>;
`;

fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
fs.writeFileSync(OUTPUT_FILE, content);

console.log(
  `Generated ${path.relative(process.cwd(), OUTPUT_FILE)}: ` +
    `${extEntries.length} extensions, ${filenameEntries.length} filenames. ` +
    `Matched ${matchedLangCount} Linguist langs to Shiki bundle, ${unmatchedLangCount} unmatched.`,
);
