// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: gozd/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct Gozd_V1_WorktreeEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var path: String = String()

  public var head: String = String()

  public var branch: String = String()

  public var isMain: Bool = false

  /// ファイル相対パス → porcelain v1 XY コード
  public var gitStatuses: Dictionary<String,String> = [:]

  public var task: Gozd_V1_Task {
    get {_task ?? Gozd_V1_Task()}
    set {_task = newValue}
  }
  /// Returns true if `task` has been explicitly set.
  public var hasTask: Bool {self._task != nil}
  /// Clears the value of `task`. Subsequent reads from it will return its default value.
  public mutating func clearTask() {self._task = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _task: Gozd_V1_Task? = nil
}

public struct Gozd_V1_Task: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: String = String()

  public var body: String = String()

  public var worktreeDir: String = String()

  public var prNumber: UInt32 = 0

  public var issueNumber: UInt32 = 0

  /// ISO 8601
  public var createdAt: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ディレクトリエントリ。fs/readDir / filer 用。
public struct Gozd_V1_FileEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  /// "file" / "directory" / "symlink"
  public var type: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_FileReadResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var content: String = String()

  public var isBinary: Bool = false

  public var isDirectory: Bool = false

  public var notFound: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitFileChange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var oldFilePath: String = String()

  public var newFilePath: String = String()

  /// "A" / "M" / "D" / "R" / "U"
  public var type: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitCommit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hash: String = String()

  public var shortHash: String = String()

  public var parents: [String] = []

  public var author: String = String()

  /// Unix timestamp（秒）
  public var date: Int64 = 0

  public var message: String = String()

  public var body: String = String()

  public var refs: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitPullRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var number: UInt32 = 0

  public var title: String = String()

  public var url: String = String()

  public var state: String = String()

  public var author: String = String()

  public var headRef: String = String()

  public var baseRef: String = String()

  public var isDraft: Bool = false

  public var assignees: [String] = []

  public var reviewers: [String] = []

  /// ISO 8601
  public var updatedAt: String = String()

  public var authorAvatarURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitIssue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var number: UInt32 = 0

  public var title: String = String()

  public var url: String = String()

  public var state: String = String()

  public var author: String = String()

  public var labels: [String] = []

  public var assignees: [String] = []

  public var updatedAt: String = String()

  public var authorAvatarURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_OpenTargetSelection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "file" / "dir"
  public var kind: String = String()

  public var relPath: String = String()

  /// 1-based
  public var lineNumber: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_ProjectConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// worktree 作成時にメインリポジトリからシンボリックリンクする相対パス一覧
  public var worktreeSymlinks: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "gozd.v1"

extension Gozd_V1_WorktreeEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WorktreeEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{1}head\0\u{1}branch\0\u{3}is_main\0\u{3}git_statuses\0\u{1}task\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.head) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.branch) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isMain) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.gitStatuses) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._task) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if !self.head.isEmpty {
      try visitor.visitSingularStringField(value: self.head, fieldNumber: 2)
    }
    if !self.branch.isEmpty {
      try visitor.visitSingularStringField(value: self.branch, fieldNumber: 3)
    }
    if self.isMain != false {
      try visitor.visitSingularBoolField(value: self.isMain, fieldNumber: 4)
    }
    if !self.gitStatuses.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.gitStatuses, fieldNumber: 5)
    }
    try { if let v = self._task {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_WorktreeEntry, rhs: Gozd_V1_WorktreeEntry) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.head != rhs.head {return false}
    if lhs.branch != rhs.branch {return false}
    if lhs.isMain != rhs.isMain {return false}
    if lhs.gitStatuses != rhs.gitStatuses {return false}
    if lhs._task != rhs._task {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_Task: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Task"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}body\0\u{3}worktree_dir\0\u{3}pr_number\0\u{3}issue_number\0\u{3}created_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.worktreeDir) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.prNumber) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.issueNumber) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.createdAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 2)
    }
    if !self.worktreeDir.isEmpty {
      try visitor.visitSingularStringField(value: self.worktreeDir, fieldNumber: 3)
    }
    if self.prNumber != 0 {
      try visitor.visitSingularUInt32Field(value: self.prNumber, fieldNumber: 4)
    }
    if self.issueNumber != 0 {
      try visitor.visitSingularUInt32Field(value: self.issueNumber, fieldNumber: 5)
    }
    if !self.createdAt.isEmpty {
      try visitor.visitSingularStringField(value: self.createdAt, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_Task, rhs: Gozd_V1_Task) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.body != rhs.body {return false}
    if lhs.worktreeDir != rhs.worktreeDir {return false}
    if lhs.prNumber != rhs.prNumber {return false}
    if lhs.issueNumber != rhs.issueNumber {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_FileEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_FileEntry, rhs: Gozd_V1_FileEntry) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_FileReadResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileReadResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}content\0\u{3}is_binary\0\u{3}is_directory\0\u{3}not_found\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isBinary) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isDirectory) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.notFound) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 1)
    }
    if self.isBinary != false {
      try visitor.visitSingularBoolField(value: self.isBinary, fieldNumber: 2)
    }
    if self.isDirectory != false {
      try visitor.visitSingularBoolField(value: self.isDirectory, fieldNumber: 3)
    }
    if self.notFound != false {
      try visitor.visitSingularBoolField(value: self.notFound, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_FileReadResult, rhs: Gozd_V1_FileReadResult) -> Bool {
    if lhs.content != rhs.content {return false}
    if lhs.isBinary != rhs.isBinary {return false}
    if lhs.isDirectory != rhs.isDirectory {return false}
    if lhs.notFound != rhs.notFound {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitFileChange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitFileChange"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}old_file_path\0\u{3}new_file_path\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.oldFilePath) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.newFilePath) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.oldFilePath.isEmpty {
      try visitor.visitSingularStringField(value: self.oldFilePath, fieldNumber: 1)
    }
    if !self.newFilePath.isEmpty {
      try visitor.visitSingularStringField(value: self.newFilePath, fieldNumber: 2)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitFileChange, rhs: Gozd_V1_GitFileChange) -> Bool {
    if lhs.oldFilePath != rhs.oldFilePath {return false}
    if lhs.newFilePath != rhs.newFilePath {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitCommit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitCommit"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}hash\0\u{3}short_hash\0\u{1}parents\0\u{1}author\0\u{1}date\0\u{1}message\0\u{1}body\0\u{1}refs\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.hash) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.shortHash) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.parents) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.date) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.refs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.hash.isEmpty {
      try visitor.visitSingularStringField(value: self.hash, fieldNumber: 1)
    }
    if !self.shortHash.isEmpty {
      try visitor.visitSingularStringField(value: self.shortHash, fieldNumber: 2)
    }
    if !self.parents.isEmpty {
      try visitor.visitRepeatedStringField(value: self.parents, fieldNumber: 3)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 4)
    }
    if self.date != 0 {
      try visitor.visitSingularInt64Field(value: self.date, fieldNumber: 5)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 6)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 7)
    }
    if !self.refs.isEmpty {
      try visitor.visitRepeatedStringField(value: self.refs, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitCommit, rhs: Gozd_V1_GitCommit) -> Bool {
    if lhs.hash != rhs.hash {return false}
    if lhs.shortHash != rhs.shortHash {return false}
    if lhs.parents != rhs.parents {return false}
    if lhs.author != rhs.author {return false}
    if lhs.date != rhs.date {return false}
    if lhs.message != rhs.message {return false}
    if lhs.body != rhs.body {return false}
    if lhs.refs != rhs.refs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitPullRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitPullRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}number\0\u{1}title\0\u{1}url\0\u{1}state\0\u{1}author\0\u{3}head_ref\0\u{3}base_ref\0\u{3}is_draft\0\u{1}assignees\0\u{1}reviewers\0\u{3}updated_at\0\u{3}author_avatar_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.number) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.headRef) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.baseRef) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.isDraft) }()
      case 9: try { try decoder.decodeRepeatedStringField(value: &self.assignees) }()
      case 10: try { try decoder.decodeRepeatedStringField(value: &self.reviewers) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.updatedAt) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.authorAvatarURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.number != 0 {
      try visitor.visitSingularUInt32Field(value: self.number, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 4)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 5)
    }
    if !self.headRef.isEmpty {
      try visitor.visitSingularStringField(value: self.headRef, fieldNumber: 6)
    }
    if !self.baseRef.isEmpty {
      try visitor.visitSingularStringField(value: self.baseRef, fieldNumber: 7)
    }
    if self.isDraft != false {
      try visitor.visitSingularBoolField(value: self.isDraft, fieldNumber: 8)
    }
    if !self.assignees.isEmpty {
      try visitor.visitRepeatedStringField(value: self.assignees, fieldNumber: 9)
    }
    if !self.reviewers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.reviewers, fieldNumber: 10)
    }
    if !self.updatedAt.isEmpty {
      try visitor.visitSingularStringField(value: self.updatedAt, fieldNumber: 11)
    }
    if !self.authorAvatarURL.isEmpty {
      try visitor.visitSingularStringField(value: self.authorAvatarURL, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitPullRequest, rhs: Gozd_V1_GitPullRequest) -> Bool {
    if lhs.number != rhs.number {return false}
    if lhs.title != rhs.title {return false}
    if lhs.url != rhs.url {return false}
    if lhs.state != rhs.state {return false}
    if lhs.author != rhs.author {return false}
    if lhs.headRef != rhs.headRef {return false}
    if lhs.baseRef != rhs.baseRef {return false}
    if lhs.isDraft != rhs.isDraft {return false}
    if lhs.assignees != rhs.assignees {return false}
    if lhs.reviewers != rhs.reviewers {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.authorAvatarURL != rhs.authorAvatarURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitIssue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitIssue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}number\0\u{1}title\0\u{1}url\0\u{1}state\0\u{1}author\0\u{1}labels\0\u{1}assignees\0\u{3}updated_at\0\u{3}author_avatar_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.number) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.labels) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.assignees) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.updatedAt) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.authorAvatarURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.number != 0 {
      try visitor.visitSingularUInt32Field(value: self.number, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 4)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 5)
    }
    if !self.labels.isEmpty {
      try visitor.visitRepeatedStringField(value: self.labels, fieldNumber: 6)
    }
    if !self.assignees.isEmpty {
      try visitor.visitRepeatedStringField(value: self.assignees, fieldNumber: 7)
    }
    if !self.updatedAt.isEmpty {
      try visitor.visitSingularStringField(value: self.updatedAt, fieldNumber: 8)
    }
    if !self.authorAvatarURL.isEmpty {
      try visitor.visitSingularStringField(value: self.authorAvatarURL, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitIssue, rhs: Gozd_V1_GitIssue) -> Bool {
    if lhs.number != rhs.number {return false}
    if lhs.title != rhs.title {return false}
    if lhs.url != rhs.url {return false}
    if lhs.state != rhs.state {return false}
    if lhs.author != rhs.author {return false}
    if lhs.labels != rhs.labels {return false}
    if lhs.assignees != rhs.assignees {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.authorAvatarURL != rhs.authorAvatarURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_OpenTargetSelection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OpenTargetSelection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{3}rel_path\0\u{3}line_number\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.relPath) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.lineNumber) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 1)
    }
    if !self.relPath.isEmpty {
      try visitor.visitSingularStringField(value: self.relPath, fieldNumber: 2)
    }
    if self.lineNumber != 0 {
      try visitor.visitSingularUInt32Field(value: self.lineNumber, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_OpenTargetSelection, rhs: Gozd_V1_OpenTargetSelection) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.relPath != rhs.relPath {return false}
    if lhs.lineNumber != rhs.lineNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_ProjectConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProjectConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}worktree_symlinks\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.worktreeSymlinks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.worktreeSymlinks.isEmpty {
      try visitor.visitRepeatedStringField(value: self.worktreeSymlinks, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ProjectConfig, rhs: Gozd_V1_ProjectConfig) -> Bool {
    if lhs.worktreeSymlinks != rhs.worktreeSymlinks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
