// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: gozd/v1/client_message.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// CLI / nc から SocketServer へ送られるメッセージ。
/// NDJSON 1 行 = 1 ClientMessage（proto3 JSON mapping）。
///
/// proto3 oneof は JSON で `{"hook":{...}}` / `{"open":{...}}` の形式になり、
/// nc 直送コマンドにそのまま埋め込める：
///
///   echo '{"hook":{"event":"session-start","ptyId":'"$GOZD_PTY_ID"'}}' | nc -w 1 -U "$GOZD_SOCKET_PATH"
public struct Gozd_V1_ClientMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var body: Gozd_V1_ClientMessage.OneOf_Body? = nil

  public var hook: Gozd_V1_HookMessage {
    get {
      if case .hook(let v)? = body {return v}
      return Gozd_V1_HookMessage()
    }
    set {body = .hook(newValue)}
  }

  public var `open`: Gozd_V1_OpenMessage {
    get {
      if case .open(let v)? = body {return v}
      return Gozd_V1_OpenMessage()
    }
    set {body = .open(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Body: Equatable, Sendable {
    case hook(Gozd_V1_HookMessage)
    case `open`(Gozd_V1_OpenMessage)

  }

  public init() {}
}

/// Claude Code の hook イベント通知。
/// 軽量な nc 直送経路では event / pty_id のみ。CLI 経由の rich 経路では
/// 残りの payload フィールドが埋まる。
public struct Gozd_V1_HookMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "session-start" / "session-end" / "running" / "done" / "needs-input" /
  /// "tool-done" / "tool-failure" / "stop-failure"
  public var event: String = String()

  public var ptyID: UInt32 = 0

  /// CLI 経由のみ
  public var lastAssistantMessage: String = String()

  public var toolName: String = String()

  /// Claude Code の tool_input をそのまま JSON 文字列として保持
  public var toolInput: String = String()

  public var isInterrupt: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// `gozd open <path>` から送られるプロジェクトを開けの指示。
public struct Gozd_V1_OpenMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var targetPath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "gozd.v1"

extension Gozd_V1_ClientMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClientMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}hook\0\u{1}open\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Gozd_V1_HookMessage?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .hook(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .hook(v)
        }
      }()
      case 2: try {
        var v: Gozd_V1_OpenMessage?
        var hadOneofValue = false
        if let current = self.body {
          hadOneofValue = true
          if case .open(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.body = .open(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.body {
    case .hook?: try {
      guard case .hook(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .open?: try {
      guard case .open(let v)? = self.body else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ClientMessage, rhs: Gozd_V1_ClientMessage) -> Bool {
    if lhs.body != rhs.body {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_HookMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HookMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}event\0\u{3}pty_id\0\u{3}last_assistant_message\0\u{3}tool_name\0\u{3}tool_input\0\u{3}is_interrupt\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.event) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.ptyID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.lastAssistantMessage) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.toolName) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.toolInput) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.isInterrupt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.event.isEmpty {
      try visitor.visitSingularStringField(value: self.event, fieldNumber: 1)
    }
    if self.ptyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.ptyID, fieldNumber: 2)
    }
    if !self.lastAssistantMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.lastAssistantMessage, fieldNumber: 3)
    }
    if !self.toolName.isEmpty {
      try visitor.visitSingularStringField(value: self.toolName, fieldNumber: 4)
    }
    if !self.toolInput.isEmpty {
      try visitor.visitSingularStringField(value: self.toolInput, fieldNumber: 5)
    }
    if self.isInterrupt != false {
      try visitor.visitSingularBoolField(value: self.isInterrupt, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_HookMessage, rhs: Gozd_V1_HookMessage) -> Bool {
    if lhs.event != rhs.event {return false}
    if lhs.ptyID != rhs.ptyID {return false}
    if lhs.lastAssistantMessage != rhs.lastAssistantMessage {return false}
    if lhs.toolName != rhs.toolName {return false}
    if lhs.toolInput != rhs.toolInput {return false}
    if lhs.isInterrupt != rhs.isInterrupt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_OpenMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OpenMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}target_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.targetPath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.targetPath.isEmpty {
      try visitor.visitSingularStringField(value: self.targetPath, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_OpenMessage, rhs: Gozd_V1_OpenMessage) -> Bool {
    if lhs.targetPath != rhs.targetPath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
