// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: gozd/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Gozd_V1_GhRefKind: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case pr // = 1
  case issue // = 2
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .pr
    case 2: self = .issue
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .pr: return 1
    case .issue: return 2
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Gozd_V1_GhRefKind] = [
    .unspecified,
    .pr,
    .issue,
  ]

}

public struct Gozd_V1_WorktreeEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var path: String = String()

  public var head: String = String()

  public var branch: String = String()

  public var isMain: Bool = false

  /// ファイル相対パス → porcelain v1 XY コード
  public var gitStatuses: Dictionary<String,String> = [:]

  public var tasks: [Gozd_V1_Task] = []

  /// upstream（追跡リモートブランチ）に対する差分。upstream 未設定なら不在。
  /// optional により「未設定」をフィールド不在で表現し、ahead/behind を見るには
  /// upstream 自体の存在をチェックする契約を型レベルで強制する。
  public var upstream: Gozd_V1_UpstreamStatus {
    get {_upstream ?? Gozd_V1_UpstreamStatus()}
    set {_upstream = newValue}
  }
  /// Returns true if `upstream` has been explicitly set.
  public var hasUpstream: Bool {self._upstream != nil}
  /// Clears the value of `upstream`. Subsequent reads from it will return its default value.
  public mutating func clearUpstream() {self._upstream = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _upstream: Gozd_V1_UpstreamStatus? = nil
}

/// upstream（追跡リモートブランチ）との差分。`git status --porcelain=v2 --branch` の
/// `# branch.ab` 行に対応。upstream 自体が未設定のときはこの message ごと不在になる。
public struct Gozd_V1_UpstreamStatus: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// upstream に対して先行しているローカルコミット数（未 push）。
  public var ahead: UInt32 = 0

  /// upstream に対して遅れているリモートコミット数（未 pull）。
  public var behind: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_Task: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// UUID。Claude session とは独立した task 固有の identity。
  public var id: String = String()

  public var worktreeDir: String = String()

  /// GitHub PR / issue 参照。GitHub の PR / issue は同一の番号空間を共有するため、
  /// 種別 + 番号の組で 1 件を表す。task 1 件あたり最大 1 つ。
  public var ghRef: Gozd_V1_GhRef {
    get {_ghRef ?? Gozd_V1_GhRef()}
    set {_ghRef = newValue}
  }
  /// Returns true if `ghRef` has been explicitly set.
  public var hasGhRef: Bool {self._ghRef != nil}
  /// Clears the value of `ghRef`. Subsequent reads from it will return its default value.
  public mutating func clearGhRef() {self._ghRef = nil}

  /// ISO 8601
  public var createdAt: String = String()

  /// 最後に attach された Claude session の ID。空文字は session 未起動 / 終了済み。
  /// SessionEnd では消さず保持し、サイドバークリック時の `claude --resume` 起点に使う。
  public var sessionID: String = String()

  /// ユーザーが明示的にターミナルを close した task かどうか。
  /// SessionEnd / terminal close (detachSession) で true に倒し、resume クリック /
  /// PR picker 再選択 / 同 sid SessionStart hook (attachSession) で false に戻す。
  /// app close (renderer 強制終了) では detachSession 経路を通らないため据え置き。
  /// サイドバー UI の "closed" / "resumable" 状態区別に使う。
  public var closedByUser: Bool = false

  /// ユーザーが UI で明示的に編集 / rename した確定値。最優先で表示に使う。
  /// 空文字は「ユーザー指定なし」(= gh_title / terminal_title へフォールバック) を意味する。
  public var userTitle: String = String()

  /// OSC ターミナルタイトル経由で観測した live 値。user_title / gh_title が空のときの
  /// 最終フォールバック。Claude が transcript 起動直後に送る placeholder ("Claude Code")
  /// は表示側で除外する。
  public var terminalTitle: String = String()

  /// PR/issue picker 取得時の snapshot タイトル。user_title が空のときの第 2 優先表示で、
  /// OSC タイトル更新では触らない (gh ↔ terminal の独立性が SSOT)。
  /// 今後 Refresh 経路で gh から再取得して上書きすることもありうる。
  public var ghTitle: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _ghRef: Gozd_V1_GhRef? = nil
}

/// GitHub PR / issue 参照。
public struct Gozd_V1_GhRef: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var kind: Gozd_V1_GhRefKind = .unspecified

  public var number: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ディレクトリエントリ。fs/readDir / filer 用。
public struct Gozd_V1_FileEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var name: String = String()

  /// "file" / "directory" / "symlink"
  public var type: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_FileReadResult: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var content: String = String()

  public var isBinary: Bool = false

  public var isDirectory: Bool = false

  public var notFound: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitFileChange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var oldFilePath: String = String()

  public var newFilePath: String = String()

  /// "A" / "M" / "D" / "R" / "U"
  public var type: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitCommit: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var hash: String = String()

  public var shortHash: String = String()

  public var parents: [String] = []

  public var author: String = String()

  /// Unix timestamp（秒）
  public var date: Int64 = 0

  public var message: String = String()

  public var body: String = String()

  public var refs: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitPullRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var number: UInt32 = 0

  public var title: String = String()

  public var url: String = String()

  public var state: String = String()

  public var author: String = String()

  public var headRef: String = String()

  public var baseRef: String = String()

  public var isDraft: Bool = false

  public var assignees: [String] = []

  public var reviewers: [String] = []

  /// ISO 8601
  public var updatedAt: String = String()

  public var authorAvatarURL: String = String()

  /// base branch の commit OID (immutable identifier)。base ref 名と異なり、
  /// fork PR / base force-push / base rename にまたがって安定して base 端を識別できる。
  /// PR diff 表示モードで「base..working tree」の base 端に使う SSOT。
  public var baseRefOid: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_GitIssue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var number: UInt32 = 0

  public var title: String = String()

  public var url: String = String()

  public var state: String = String()

  public var author: String = String()

  public var labels: [String] = []

  public var assignees: [String] = []

  public var updatedAt: String = String()

  public var authorAvatarURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_OpenTargetSelection: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "file" / "dir"
  public var kind: String = String()

  public var relPath: String = String()

  /// 1-based
  public var lineNumber: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_ProjectConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// worktree 作成時にメインリポジトリからシンボリックリンクする相対パス一覧
  public var worktreeSymlinks: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "gozd.v1"

extension Gozd_V1_GhRefKind: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GH_REF_KIND_UNSPECIFIED\0\u{1}GH_REF_KIND_PR\0\u{1}GH_REF_KIND_ISSUE\0")
}

extension Gozd_V1_WorktreeEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WorktreeEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}path\0\u{1}head\0\u{1}branch\0\u{3}is_main\0\u{3}git_statuses\0\u{1}tasks\0\u{1}upstream\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.head) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.branch) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isMain) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.gitStatuses) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.tasks) }()
      case 7: try { try decoder.decodeSingularMessageField(value: &self._upstream) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 1)
    }
    if !self.head.isEmpty {
      try visitor.visitSingularStringField(value: self.head, fieldNumber: 2)
    }
    if !self.branch.isEmpty {
      try visitor.visitSingularStringField(value: self.branch, fieldNumber: 3)
    }
    if self.isMain != false {
      try visitor.visitSingularBoolField(value: self.isMain, fieldNumber: 4)
    }
    if !self.gitStatuses.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.gitStatuses, fieldNumber: 5)
    }
    if !self.tasks.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.tasks, fieldNumber: 6)
    }
    try { if let v = self._upstream {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_WorktreeEntry, rhs: Gozd_V1_WorktreeEntry) -> Bool {
    if lhs.path != rhs.path {return false}
    if lhs.head != rhs.head {return false}
    if lhs.branch != rhs.branch {return false}
    if lhs.isMain != rhs.isMain {return false}
    if lhs.gitStatuses != rhs.gitStatuses {return false}
    if lhs.tasks != rhs.tasks {return false}
    if lhs._upstream != rhs._upstream {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_UpstreamStatus: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpstreamStatus"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ahead\0\u{1}behind\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.ahead) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.behind) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ahead != 0 {
      try visitor.visitSingularUInt32Field(value: self.ahead, fieldNumber: 1)
    }
    if self.behind != 0 {
      try visitor.visitSingularUInt32Field(value: self.behind, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_UpstreamStatus, rhs: Gozd_V1_UpstreamStatus) -> Bool {
    if lhs.ahead != rhs.ahead {return false}
    if lhs.behind != rhs.behind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_Task: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Task"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{4}\u{2}worktree_dir\0\u{3}gh_ref\0\u{3}created_at\0\u{3}session_id\0\u{3}closed_by_user\0\u{3}user_title\0\u{3}terminal_title\0\u{3}gh_title\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.worktreeDir) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._ghRef) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.createdAt) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self.closedByUser) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.userTitle) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.terminalTitle) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.ghTitle) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 1)
    }
    if !self.worktreeDir.isEmpty {
      try visitor.visitSingularStringField(value: self.worktreeDir, fieldNumber: 3)
    }
    try { if let v = self._ghRef {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.createdAt.isEmpty {
      try visitor.visitSingularStringField(value: self.createdAt, fieldNumber: 5)
    }
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 6)
    }
    if self.closedByUser != false {
      try visitor.visitSingularBoolField(value: self.closedByUser, fieldNumber: 7)
    }
    if !self.userTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.userTitle, fieldNumber: 8)
    }
    if !self.terminalTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.terminalTitle, fieldNumber: 9)
    }
    if !self.ghTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.ghTitle, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_Task, rhs: Gozd_V1_Task) -> Bool {
    if lhs.id != rhs.id {return false}
    if lhs.worktreeDir != rhs.worktreeDir {return false}
    if lhs._ghRef != rhs._ghRef {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.closedByUser != rhs.closedByUser {return false}
    if lhs.userTitle != rhs.userTitle {return false}
    if lhs.terminalTitle != rhs.terminalTitle {return false}
    if lhs.ghTitle != rhs.ghTitle {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GhRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GhRef"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{1}number\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.kind) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.number) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.kind != .unspecified {
      try visitor.visitSingularEnumField(value: self.kind, fieldNumber: 1)
    }
    if self.number != 0 {
      try visitor.visitSingularUInt32Field(value: self.number, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GhRef, rhs: Gozd_V1_GhRef) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.number != rhs.number {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_FileEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_FileEntry, rhs: Gozd_V1_FileEntry) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_FileReadResult: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".FileReadResult"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}content\0\u{3}is_binary\0\u{3}is_directory\0\u{3}not_found\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isBinary) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isDirectory) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.notFound) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 1)
    }
    if self.isBinary != false {
      try visitor.visitSingularBoolField(value: self.isBinary, fieldNumber: 2)
    }
    if self.isDirectory != false {
      try visitor.visitSingularBoolField(value: self.isDirectory, fieldNumber: 3)
    }
    if self.notFound != false {
      try visitor.visitSingularBoolField(value: self.notFound, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_FileReadResult, rhs: Gozd_V1_FileReadResult) -> Bool {
    if lhs.content != rhs.content {return false}
    if lhs.isBinary != rhs.isBinary {return false}
    if lhs.isDirectory != rhs.isDirectory {return false}
    if lhs.notFound != rhs.notFound {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitFileChange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitFileChange"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}old_file_path\0\u{3}new_file_path\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.oldFilePath) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.newFilePath) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.oldFilePath.isEmpty {
      try visitor.visitSingularStringField(value: self.oldFilePath, fieldNumber: 1)
    }
    if !self.newFilePath.isEmpty {
      try visitor.visitSingularStringField(value: self.newFilePath, fieldNumber: 2)
    }
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitFileChange, rhs: Gozd_V1_GitFileChange) -> Bool {
    if lhs.oldFilePath != rhs.oldFilePath {return false}
    if lhs.newFilePath != rhs.newFilePath {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitCommit: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitCommit"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}hash\0\u{3}short_hash\0\u{1}parents\0\u{1}author\0\u{1}date\0\u{1}message\0\u{1}body\0\u{1}refs\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.hash) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.shortHash) }()
      case 3: try { try decoder.decodeRepeatedStringField(value: &self.parents) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.date) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.message) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.body) }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.refs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.hash.isEmpty {
      try visitor.visitSingularStringField(value: self.hash, fieldNumber: 1)
    }
    if !self.shortHash.isEmpty {
      try visitor.visitSingularStringField(value: self.shortHash, fieldNumber: 2)
    }
    if !self.parents.isEmpty {
      try visitor.visitRepeatedStringField(value: self.parents, fieldNumber: 3)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 4)
    }
    if self.date != 0 {
      try visitor.visitSingularInt64Field(value: self.date, fieldNumber: 5)
    }
    if !self.message.isEmpty {
      try visitor.visitSingularStringField(value: self.message, fieldNumber: 6)
    }
    if !self.body.isEmpty {
      try visitor.visitSingularStringField(value: self.body, fieldNumber: 7)
    }
    if !self.refs.isEmpty {
      try visitor.visitRepeatedStringField(value: self.refs, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitCommit, rhs: Gozd_V1_GitCommit) -> Bool {
    if lhs.hash != rhs.hash {return false}
    if lhs.shortHash != rhs.shortHash {return false}
    if lhs.parents != rhs.parents {return false}
    if lhs.author != rhs.author {return false}
    if lhs.date != rhs.date {return false}
    if lhs.message != rhs.message {return false}
    if lhs.body != rhs.body {return false}
    if lhs.refs != rhs.refs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitPullRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitPullRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}number\0\u{1}title\0\u{1}url\0\u{1}state\0\u{1}author\0\u{3}head_ref\0\u{3}base_ref\0\u{3}is_draft\0\u{1}assignees\0\u{1}reviewers\0\u{3}updated_at\0\u{3}author_avatar_url\0\u{3}base_ref_oid\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.number) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.headRef) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.baseRef) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self.isDraft) }()
      case 9: try { try decoder.decodeRepeatedStringField(value: &self.assignees) }()
      case 10: try { try decoder.decodeRepeatedStringField(value: &self.reviewers) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.updatedAt) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.authorAvatarURL) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self.baseRefOid) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.number != 0 {
      try visitor.visitSingularUInt32Field(value: self.number, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 4)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 5)
    }
    if !self.headRef.isEmpty {
      try visitor.visitSingularStringField(value: self.headRef, fieldNumber: 6)
    }
    if !self.baseRef.isEmpty {
      try visitor.visitSingularStringField(value: self.baseRef, fieldNumber: 7)
    }
    if self.isDraft != false {
      try visitor.visitSingularBoolField(value: self.isDraft, fieldNumber: 8)
    }
    if !self.assignees.isEmpty {
      try visitor.visitRepeatedStringField(value: self.assignees, fieldNumber: 9)
    }
    if !self.reviewers.isEmpty {
      try visitor.visitRepeatedStringField(value: self.reviewers, fieldNumber: 10)
    }
    if !self.updatedAt.isEmpty {
      try visitor.visitSingularStringField(value: self.updatedAt, fieldNumber: 11)
    }
    if !self.authorAvatarURL.isEmpty {
      try visitor.visitSingularStringField(value: self.authorAvatarURL, fieldNumber: 12)
    }
    if !self.baseRefOid.isEmpty {
      try visitor.visitSingularStringField(value: self.baseRefOid, fieldNumber: 13)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitPullRequest, rhs: Gozd_V1_GitPullRequest) -> Bool {
    if lhs.number != rhs.number {return false}
    if lhs.title != rhs.title {return false}
    if lhs.url != rhs.url {return false}
    if lhs.state != rhs.state {return false}
    if lhs.author != rhs.author {return false}
    if lhs.headRef != rhs.headRef {return false}
    if lhs.baseRef != rhs.baseRef {return false}
    if lhs.isDraft != rhs.isDraft {return false}
    if lhs.assignees != rhs.assignees {return false}
    if lhs.reviewers != rhs.reviewers {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.authorAvatarURL != rhs.authorAvatarURL {return false}
    if lhs.baseRefOid != rhs.baseRefOid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_GitIssue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GitIssue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}number\0\u{1}title\0\u{1}url\0\u{1}state\0\u{1}author\0\u{1}labels\0\u{1}assignees\0\u{3}updated_at\0\u{3}author_avatar_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.number) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.title) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.state) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.author) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.labels) }()
      case 7: try { try decoder.decodeRepeatedStringField(value: &self.assignees) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.updatedAt) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.authorAvatarURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.number != 0 {
      try visitor.visitSingularUInt32Field(value: self.number, fieldNumber: 1)
    }
    if !self.title.isEmpty {
      try visitor.visitSingularStringField(value: self.title, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.state.isEmpty {
      try visitor.visitSingularStringField(value: self.state, fieldNumber: 4)
    }
    if !self.author.isEmpty {
      try visitor.visitSingularStringField(value: self.author, fieldNumber: 5)
    }
    if !self.labels.isEmpty {
      try visitor.visitRepeatedStringField(value: self.labels, fieldNumber: 6)
    }
    if !self.assignees.isEmpty {
      try visitor.visitRepeatedStringField(value: self.assignees, fieldNumber: 7)
    }
    if !self.updatedAt.isEmpty {
      try visitor.visitSingularStringField(value: self.updatedAt, fieldNumber: 8)
    }
    if !self.authorAvatarURL.isEmpty {
      try visitor.visitSingularStringField(value: self.authorAvatarURL, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_GitIssue, rhs: Gozd_V1_GitIssue) -> Bool {
    if lhs.number != rhs.number {return false}
    if lhs.title != rhs.title {return false}
    if lhs.url != rhs.url {return false}
    if lhs.state != rhs.state {return false}
    if lhs.author != rhs.author {return false}
    if lhs.labels != rhs.labels {return false}
    if lhs.assignees != rhs.assignees {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.authorAvatarURL != rhs.authorAvatarURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_OpenTargetSelection: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OpenTargetSelection"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{3}rel_path\0\u{3}line_number\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.relPath) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.lineNumber) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 1)
    }
    if !self.relPath.isEmpty {
      try visitor.visitSingularStringField(value: self.relPath, fieldNumber: 2)
    }
    if self.lineNumber != 0 {
      try visitor.visitSingularUInt32Field(value: self.lineNumber, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_OpenTargetSelection, rhs: Gozd_V1_OpenTargetSelection) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.relPath != rhs.relPath {return false}
    if lhs.lineNumber != rhs.lineNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_ProjectConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ProjectConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}worktree_symlinks\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.worktreeSymlinks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.worktreeSymlinks.isEmpty {
      try visitor.visitRepeatedStringField(value: self.worktreeSymlinks, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ProjectConfig, rhs: Gozd_V1_ProjectConfig) -> Bool {
    if lhs.worktreeSymlinks != rhs.worktreeSymlinks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
