// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: gozd/v1/claude_session.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// 指定 PTY に紐づく Claude セッションを永続化から削除する。renderer の
/// unregisterPane（terminal.closePane / resetLayout / worktree 削除）から呼ぶ。
/// session-end hook 経路ではなく PTY 単位の明示的削除なので、worktree_path も
/// 併せて受け取って projectKey 解決を確定させる。pty_id に紐づく sessionId は
/// native 側の PTYRegistry が保持する。
public struct Gozd_V1_ClaudeSessionRemoveByPtyRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var ptyID: UInt32 = 0

  public var worktreePath: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_ClaudeSessionRemoveByPtyResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 削除した session_id。renderer が repoStore の WorktreeEntry.tasks から
  /// 該当 Task を即時削除するために使う。pty に session が紐付いていなかった
  /// 場合は空文字。
  public var removedSessionID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Claude Code が ~/.claude/projects/<cwd エンコード>/<session_id>.jsonl に書き出した
/// セッションログ (JSONL) を読む。サイドバー task メニューの「セッションログ表示」用。
///
/// cwd → ディレクトリ名のエンコード規則 (`/` `.` → `-` 等) は Claude 側の内部仕様で
/// 将来変わりうるため、renderer から cwd を渡して native でパス再構成する設計は取らない。
/// session_id は UUID で一意なので、native 側が ~/.claude/projects/*/<session_id>.jsonl を
/// glob 解決する。これにより fork で別ファイルに分裂したセッションも自分の session_id を
/// ファイル名に持つ 1 ファイルとして確実に引ける。
public struct Gozd_V1_ClaudeSessionLogRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sessionID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// セッションログ 1 本分 (main または subagent)。parse は renderer 側が担う。
public struct Gozd_V1_ClaudeSessionLogEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "main" (本体セッション) または "subagent" (Task / Workflow ツールで起動したサブエージェント)。
  /// workflow agent かどうかは workflow_run_id の有無で判別する。
  public var kind: String = String()

  /// main は session_id、subagent は agent_id。
  public var id: String = String()

  /// subagent のラベル (meta.json の description)。main は空文字。
  public var label: String = String()

  /// subagent の agentType (meta.json)。main は空文字。
  public var agentType: String = String()

  /// jsonl の絶対パス。
  public var path: String = String()

  /// jsonl の生内容 (改行区切り)。
  public var content: String = String()

  /// この subagent を spawn した main 側 Agent tool_use の id (meta.json の toolUseId)。
  /// main の Agent tool_use と subagent を結ぶキー。main entry は空文字。
  /// SendMessage による resume は別キー (main tool_use の input.to == この entry の id or name)
  /// で結ぶため、この field には現れない (resume では新規 subagent が作られないため)。
  public var parentToolUseID: String = String()

  /// subagent の名前 (meta.json の name)。SendMessage の input.to は agent_id だけでなく
  /// agent name のこともあるため、id と name の双方で resume を紐付けられるよう露出する。
  /// 名前付きで起動していない subagent / main は空文字。
  public var name: String = String()

  /// この subagent が属する workflow run の id (wf_xxx)。Workflow ツールが spawn した
  /// workflow agent のみ非空。Task ツール subagent / main は空文字。main の Workflow
  /// tool_use と結ぶグループキー (main の Workflow tool_result の "Run ID: wf_xxx" と一致)。
  public var workflowRunID: String = String()

  /// workflow の表示名 (<sessionId>/workflows/<wf_id>.json の workflowName)。
  /// タブバーのグループ見出しに使う。非 workflow subagent / main は空文字。
  public var workflowName: String = String()

  /// workflow agent の phase 名 (workflowProgress の phaseTitle)。タブのラベルに使う。
  /// 非 workflow subagent / main は空文字。
  public var phaseTitle: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Gozd_V1_ClaudeSessionLogResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// main の jsonl が glob で見つかったか。未起動 / cleanup 済みセッションでは false。
  public var found: Bool = false

  /// entries[0] が main、残りが subagents (見つかった順)。found=false なら空。
  /// Task ツール subagent は ~/.claude/projects/<encoded>/<session_id>/subagents/agent-*.jsonl、
  /// Workflow agent は同 subagents/workflows/<wf_id>/agent-*.jsonl に isSidechain ログとして
  /// 並ぶ。main の projectDir を起点に両方を列挙する。
  public var entries: [Gozd_V1_ClaudeSessionLogEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "gozd.v1"

extension Gozd_V1_ClaudeSessionRemoveByPtyRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClaudeSessionRemoveByPtyRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}pty_id\0\u{3}worktree_path\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.ptyID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.worktreePath) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.ptyID != 0 {
      try visitor.visitSingularUInt32Field(value: self.ptyID, fieldNumber: 1)
    }
    if !self.worktreePath.isEmpty {
      try visitor.visitSingularStringField(value: self.worktreePath, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ClaudeSessionRemoveByPtyRequest, rhs: Gozd_V1_ClaudeSessionRemoveByPtyRequest) -> Bool {
    if lhs.ptyID != rhs.ptyID {return false}
    if lhs.worktreePath != rhs.worktreePath {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_ClaudeSessionRemoveByPtyResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClaudeSessionRemoveByPtyResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}removed_session_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.removedSessionID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.removedSessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.removedSessionID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ClaudeSessionRemoveByPtyResponse, rhs: Gozd_V1_ClaudeSessionRemoveByPtyResponse) -> Bool {
    if lhs.removedSessionID != rhs.removedSessionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_ClaudeSessionLogRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClaudeSessionLogRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}session_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.sessionID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.sessionID.isEmpty {
      try visitor.visitSingularStringField(value: self.sessionID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ClaudeSessionLogRequest, rhs: Gozd_V1_ClaudeSessionLogRequest) -> Bool {
    if lhs.sessionID != rhs.sessionID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_ClaudeSessionLogEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClaudeSessionLogEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}kind\0\u{1}id\0\u{1}label\0\u{3}agent_type\0\u{1}path\0\u{1}content\0\u{3}parent_tool_use_id\0\u{1}name\0\u{3}workflow_run_id\0\u{3}workflow_name\0\u{3}phase_title\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.kind) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.id) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.label) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.agentType) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.path) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.content) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.parentToolUseID) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.workflowRunID) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.workflowName) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.phaseTitle) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.kind.isEmpty {
      try visitor.visitSingularStringField(value: self.kind, fieldNumber: 1)
    }
    if !self.id.isEmpty {
      try visitor.visitSingularStringField(value: self.id, fieldNumber: 2)
    }
    if !self.label.isEmpty {
      try visitor.visitSingularStringField(value: self.label, fieldNumber: 3)
    }
    if !self.agentType.isEmpty {
      try visitor.visitSingularStringField(value: self.agentType, fieldNumber: 4)
    }
    if !self.path.isEmpty {
      try visitor.visitSingularStringField(value: self.path, fieldNumber: 5)
    }
    if !self.content.isEmpty {
      try visitor.visitSingularStringField(value: self.content, fieldNumber: 6)
    }
    if !self.parentToolUseID.isEmpty {
      try visitor.visitSingularStringField(value: self.parentToolUseID, fieldNumber: 7)
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 8)
    }
    if !self.workflowRunID.isEmpty {
      try visitor.visitSingularStringField(value: self.workflowRunID, fieldNumber: 9)
    }
    if !self.workflowName.isEmpty {
      try visitor.visitSingularStringField(value: self.workflowName, fieldNumber: 10)
    }
    if !self.phaseTitle.isEmpty {
      try visitor.visitSingularStringField(value: self.phaseTitle, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ClaudeSessionLogEntry, rhs: Gozd_V1_ClaudeSessionLogEntry) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.id != rhs.id {return false}
    if lhs.label != rhs.label {return false}
    if lhs.agentType != rhs.agentType {return false}
    if lhs.path != rhs.path {return false}
    if lhs.content != rhs.content {return false}
    if lhs.parentToolUseID != rhs.parentToolUseID {return false}
    if lhs.name != rhs.name {return false}
    if lhs.workflowRunID != rhs.workflowRunID {return false}
    if lhs.workflowName != rhs.workflowName {return false}
    if lhs.phaseTitle != rhs.phaseTitle {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Gozd_V1_ClaudeSessionLogResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ClaudeSessionLogResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}found\0\u{1}entries\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.found) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.entries) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.found != false {
      try visitor.visitSingularBoolField(value: self.found, fieldNumber: 1)
    }
    if !self.entries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.entries, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Gozd_V1_ClaudeSessionLogResponse, rhs: Gozd_V1_ClaudeSessionLogResponse) -> Bool {
    if lhs.found != rhs.found {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
